# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='auth_server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120, unique=True, verbose_name='WEB_SERVER_DNS')),
                ('ip', models.CharField(default='', max_length=120, verbose_name='RADIUS_SERVER_IP')),
            ],
        ),
        migrations.CreateModel(
            name='device_ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120, unique=True, verbose_name='WIFI_DEVICE_IP')),
                ('mac', models.CharField(default='00:00:00:00:00:00', max_length=120, unique=True, verbose_name='MAC_ADDRESS')),
            ],
        ),
        migrations.CreateModel(
            name='ssid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='SSID_NAME')),
                ('status', models.IntegerField(verbose_name='SSID_STATUS')),
                ('acl', models.CharField(blank=True, max_length=120, verbose_name='ACL_ON_DEVICE')),
                ('wlan_id', models.CharField(default='', max_length=120, verbose_name='WLAN_ID')),
                ('ap_mac', models.CharField(default='00:00:00:00:00:00', max_length=120, verbose_name='AP_MAC')),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='GROUP_NAME')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssid.device_ip')),
            ],
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120, unique=True, verbose_name='SSID_VENDOR')),
            ],
        ),
        migrations.AddField(
            model_name='ssid',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssid.vendor'),
        ),
        migrations.AddField(
            model_name='ssid',
            name='web',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssid.auth_server'),
        ),
        migrations.AddField(
            model_name='device_ip',
            name='vendor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ssid.vendor'),
        ),
    ]
