# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ssid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('status', models.IntegerField()),
                ('vendor', models.CharField(max_length=120)),
                ('ip', models.CharField(max_length=120)),
                ('radius', models.CharField(max_length=120)),
                ('web', models.CharField(max_length=120)),
                ('acl', models.CharField(max_length=120)),
            ],
        ),
    ]
