# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssid', '0003_auto_20170322_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssid',
            name='status',
            field=models.IntegerField(default=0, verbose_name='SSID_STATUS'),
        ),
    ]
