# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssid', '0004_auto_20170322_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_server',
            name='name',
            field=models.CharField(default='', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='device_ip',
            name='name',
            field=models.CharField(default='', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='ssid',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssid.device_ip', verbose_name='WIFI_DEVICE_IP'),
        ),
        migrations.AlterField(
            model_name='ssid',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssid.vendor', verbose_name='SSID_VENDOR'),
        ),
        migrations.AlterField(
            model_name='ssid',
            name='web',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssid.auth_server', verbose_name='WEB_SERVER_DNS'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(default='', max_length=120, unique=True),
        ),
    ]
