# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgshare', '0008_auto_20161123_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='view_date',
            field=models.DateTimeField(default='2016-11-23 11:26:40'),
        ),
    ]
