# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 10:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgshare', '0009_auto_20161123_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 23, 12, 30, 43, 234135)),
        ),
        migrations.AlterField(
            model_name='img',
            name='view_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 23, 12, 30, 43, 234135)),
        ),
    ]
