# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgshare', '0010_auto_20161123_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='upload_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='img',
            name='view_date',
            field=models.DateTimeField(),
        ),
    ]
