# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgshare', '0011_auto_20161123_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
