# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgshare', '0012_img_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='key',
            field=models.SlugField(default='34u7', max_length=10, unique=True),
        ),
    ]
