# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgshare', '0013_auto_20161124_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img',
            old_name='like',
            new_name='like_count',
        ),
        migrations.AlterField(
            model_name='img',
            name='key',
            field=models.SlugField(default='GK7X', max_length=10, unique=True),
        ),
    ]
